# Generated by Django 5.2.17 on 2026-08-25 20:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.TextField()),
                ("org_type", models.TextField()),
                ("name", models.TextField()),
                ("slug", models.CharField(max_length=100)),
                ("public_email", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("website_url", models.TextField(blank=True, null=True)),
                ("hours_text", models.TextField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("department_id", models.TextField(blank=True, null=True)),
                ("parent_department_id", models.TextField(blank=True, null=True)),
                ("address_mailing", models.TextField(blank=True, null=True)),
                ("address_physical", models.TextField(blank=True, null=True)),
                ("additional_information", models.TextField(blank=True, null=True)),
                ("fax", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organizations_organization",
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "name"],
                        name="organizatio_tenant__aa177a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "slug", "org_type"),
                        name="uq_orgs_tenant_slug_org_type",
                    )
                ],
            },
        ),
    ]
