# Generated by Django 5.2.17 on 2026-08-25 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.TextField()),
                ("seat_no", models.IntegerField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("job_title", models.TextField(blank=True, null=True)),
                ("created_at", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receives_financial_reports",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "db_table": "assignments_assignment",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("person__isnull", False)),
                        fields=("tenant_id", "person", "org", "seat_no"),
                        name="uq_assignments_tenant_person_org_seat",
                    )
                ],
            },
        ),
    ]
