# Generated by Django 5.2.17 on 2026-08-25 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.TextField()),
                ("actor", models.TextField()),
                ("action", models.TextField()),
                ("entity_type", models.TextField()),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("details", models.JSONField(default=dict)),
                ("ts", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "audit_auditlog",
                "permissions": [("revert_auditlog", "Can revert a directory mutation")],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-ts"],
                        name="audit_audit_tenant__74de99_idx",
                    )
                ],
            },
        ),
    ]
