# Generated by Django 5.2.17 on 2026-08-25 20:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.TextField()),
                ("employee_id", models.TextField(blank=True, null=True)),
                ("name_first", models.TextField(blank=True, null=True)),
                ("name_middle", models.TextField(blank=True, null=True)),
                ("name_last", models.TextField(blank=True, null=True)),
                ("name_suffix", models.TextField(blank=True, null=True)),
                ("full_name", models.TextField(blank=True, null=True)),
                ("email_public", models.TextField(blank=True, null=True)),
                ("phone_public", models.TextField(blank=True, null=True)),
                ("phone_public_ext", models.TextField(blank=True, null=True)),
                ("job_title", models.TextField(blank=True, null=True)),
                ("person_key", models.TextField(blank=True, null=True)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("show_in_directory", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "people_person",
                "permissions": [
                    (
                        "trigger_wordpress_sync",
                        "Can trigger WordPress sync for a person",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "name_last", "name_first"],
                        name="people_pers_tenant__60e36c_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "person_key"],
                        name="people_pers_tenant__985d34_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("employee_id__isnull", False),
                            models.Q(("employee_id", ""), _negated=True),
                        ),
                        fields=("tenant_id", "employee_id"),
                        name="uq_people_tenant_employee",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("person_key__isnull", False),
                            models.Q(("person_key", ""), _negated=True),
                        ),
                        fields=("person_key",),
                        name="uq_people_person_key",
                    ),
                ],
            },
        ),
    ]
